name: Build Image and Push to Dockerhub

on: push

jobs:
  deploy_compose:
    name: Build Image and Push to Dockerhub
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build image
        run: docker-compose build

      - name: push Docker Compose services
        run: docker push ${{ secrets.DOCKER_USERNAME }}/finalassesment_app:latest